From bug 55:     'varBadSuffix' when cajoling 'onclick="foo(this)"'
    <a onclick="foo(this)">hi</a>

    result is:
    
    FATAL_ERROR: Variables cannot end in "__": Rule "varBadSuffix",
      Reference Identifier : thisNode___


Fixed rewriting of event handlers in HTML.
Order of arguments was wrong, and the clone in MultipleQuasiHole
was causing nodes to lose their synthetic property before being
rewritten.