Adding support for downlevel-revealed type of IE conditional comments <unassigned>
wnlevel revealed type of conditional comments (of the following type) are not
handled correctly in the parser:
<![if ! IE]>
<link rel="stylesheet" href="special.css" type="text/css" />
<![endif]>

These result in the following exception while parsing the page (due to the node
being interpreted as an IE_COMMENT, but not having the <!-- and --> markers):
java.lang.StringIndexOutOfBoundsException: String index out of range: -5
	at java.lang.String.substring(String.java:1949)
	at
com.google.caja.parser.html.Html5ElementStack.processComment(Html5ElementStack.java:459)
	at com.google.caja.parser.html.DomParser.parseDom(DomParser.java:589)
	at com.google.caja.parser.html.DomParser.parseDocument(DomParser.java:206)
	at com.google.caja.parser.html.DomParser.parseDocument(DomParser.java:192)

In this patch, we fix this by handling both downlevel-hidden and
downlevel-revealed type of comments, at the same time ensuring that "<!CDATA"
tags are not mixed up with "<!if IE" kind of tags in the HtmlLexer.

http://codereview.appspot.com/4670048/

Patch from Anupama, Thanks

R=pulkitgoyal2000@gmail.com